name: resnet18 #34
#+ backend: torch

num_parameters: [1, 2, 4, 8, 16, 32, 64] #[64, 32, 16, 8, 4, 2, 1]
#num_parameters: [64] # for prototyping

torchvision_params:
  weights: Null
    # - Null
    # - -__:
    #     value: torchvision.models.ResNet18_Weights
    #     eval: eval

#output_size: 1

optimizer:
  name: Adam
  params:
    lr: 1.0e-3 # 0.2
    #weight_decay: 0.0005

loss: NCODLoss #NCODLoss #ForwardNRL #CrossEntropyLoss

# loss:
#   GCELoss:
#     q: 0.7

metrics:
  - SoftLabelsAccuracy

log_params:
  on_epoch: True

#seed: ${exp.seed}

+loader_params: loader_params_cfg

+trainer_params: trainer_params_cfg