/accelerator: gpu #cpu
/enable_checkpointing: True
max_epochs: 4000 #10
callbacks:
    # - EarlyStopping:
    #     monitor: val_loss #val_loss/dataloader_idx_0 when using multiple dataloaders
    #     mode: min
    #     patience: 10
    #     #verbose: True

    - ModelCheckpoint:
        /dirpath: ${__exp__.project_folder}/out/models/${__exp__.name}/
        /filename: best
        save_top_k: 1
        save_last: True
        monitor: val_loss/dataloader_idx_0 #val_loss (metrics on validation set idx = 0, test set = 1)
        mode: min
        #verbose: True
/logger: #pl.loggers.CSVLogger("../out/log", name=str(experiment_id))
    name: CSVLogger
    params:
        save_dir: ${__exp__.project_folder}/out/log/${__exp__.name}/